flowに関する処理
ISC-BusinessFlow/BusinessFlow pull request #14
Opened 2021-10-27 05:40 UTC by TTTTk84

Fix #13

2021-11-09 01:06 UTC, DuGlaser commented
@TTTTk84 
PRありがとうございます！
まだ作業中かもしれませんが、レビューして問題ない場合はDraftからOpenにしてコメントいただけると:pray:

2021-11-09 07:33 UTC, TTTTk84 commented
了解です。
openにしました！

2021-11-10 01:14 UTC, DuGlaser requested changes
@TTTTk84 
お疲れ様です！ #16 の影響で私のローカル上では動作確認ができなかったため、一旦簡単にレビューさせていただきました:pray:
ご確認お願いします！

2021-11-17 00:54 UTC, TTTTk84 commented on backend/prisma/schema.prisma
> +  flowId     Int
修正しました！

2021-11-17 00:54 UTC, TTTTk84 commented on backend/src/app.ts
> +});
修正しました！

2021-11-17 00:55 UTC, TTTTk84 commented on backend/src/controller/flowController.ts
> +    console.log("temp");
修正しました！

2021-11-17 00:55 UTC, TTTTk84 commented on backend/src/controller/flowController.ts
> +    res.status(200).send(`success create ${flow.name}`);
修正しました！

2021-11-17 00:55 UTC, TTTTk84 commented on backend/src/controller/flowController.ts
> +    res.status(500).send("error create flow");
修正しました！

2021-11-17 00:55 UTC, TTTTk84 commented on backend/src/controller/flowController.ts
> +    res.status(500).send("error delete todo");
修正しました！

2021-11-17 02:41 UTC, TTTTk84 commented
レビューありがとうございます！

2021-11-19 10:21 UTC, TTTTk84 commented
レビューよろしくお願いします！

2021-11-19 10:30 UTC, DuGlaser requested changes
@TTTTk84 
ありがとうございます！全体的に良さそうです:+1:
数点だけ細かいところになりますがコメントしましたので変更お願いします！

2021-11-19 10:30 UTC, DuGlaser commented on backend/src/controller/flowController.ts
> +    const updated_flow = await prisma.flow.update({
JSはキャメルケースのほうがいいと思います！

2021-11-19 10:30 UTC, DuGlaser commented on backend/src/controller/flowController.ts
> +// GET /flows/:id
すごい細かいところになってしまうが、他のコメントと書き方を統一するとよりいいかなと思いました！

2021-11-19 10:44 UTC, DuGlaser approved these changes
ありがとうございます！良さそうです！

2021-11-19 10:44 UTC, merged