Issue 33
ISC-BusinessFlow/BusinessFlow pull request #54
Opened 2022-01-04 03:35 UTC by n0s3nsE

2022-01-04 04:11 UTC, DuGlaser requested changes
@shinooooo @n0s3nsE 
お疲れ様です！こちらレビューしましたので修正お願いします！

2022-01-04 04:11 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +    <FlowCard />
上と同様で配列状のFlowを受け取ってそれをmapで回して表示する形がいいと思います！また、複数の同一のコンポーネントを表示する際にはkeyを指定してあげる必要があると思います！

2022-01-04 04:11 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +const FlowCard = () => (
こちらも同様でpropsとしてtitleやcreatedAtなどを受け渡せる形にしておいたほうがいいと思います！

2022-01-04 04:11 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +          </svg>
これは`KebabMenuIcon`などのようなコンポーネントとして切り出したほうがいいかなと思いました！
そのほうが再利用が効きますし、何よりどういったIconなのかが非常にわかりやすくなります！(これを見ただけだと実際に表示するまでどういったIconかわかりづらい)

2022-01-04 04:11 UTC, DuGlaser commented on frontend/src/components/new/ToolbarComponent.tsx
> +    <div className={styles.toolbar}>
こちらはclassNameを指定する形ではなくChakraの`Box`を使ってpropsでstyleを指定する形にするのなおいいかなと思います！

2022-01-04 04:11 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +export default FlowList;
好みの問題もあるかもしれませんがnamed exportにしたほうがいいかなと思います！(このプロジェクトだと他のところがすでにそうなっているので、そのほうが統一感が出ます)

2022-01-04 04:11 UTC, DuGlaser commented on frontend/src/components/new/ToolbarComponent.tsx
> +export default Toolbar;
好みの問題もあるかもしれませんがnamed exportにしたほうがいいかなと思います！(このプロジェクトだと他のところがすでにそうなっているので、そのほうが統一感が出ます)

2022-01-04 04:11 UTC, DuGlaser commented on frontend/src/pages/new.tsx
> +export default New;
すいません！先日`pages/new`にしようと言ったのですが、`pages/index`のほうが自然かなと思ったので修正お願いします:bow:

2022-01-04 04:16 UTC, DuGlaser reviewed
![Screenshot from 2022-01-04 13-13-24](https://user-images.githubusercontent.com/50506482/148008719-3924b3eb-e9c2-412e-9381-d2750bb5ca0f.png)

ToolbarとFlowListの間にもう少し余白があったほうがいいかなと思うのですがいかがでしょうか！

2022-01-04 04:37 UTC, n0s3nsE commented on frontend/src/pages/new.tsx
> +export default New;
既に存在しているindex.tsxはテストのような物なので、自分は問題ないと思うのですが
pages/index.tsx → 削除
new.tsx→index.tsx
という感じにやっちゃって問題ないですか？

2022-01-04 04:38 UTC, DuGlaser commented on frontend/src/pages/new.tsx
> +export default New;
そちらで問題ないです！お願いします！

2022-01-04 10:08 UTC, shinooooo commented on frontend/src/components/new/FlowListComponent.tsx
> +const FlowCard = ({ title, createdAt }: FLowListType) => (
mapメソッドを用いた場合はkeyを付けろとeslintに指摘されましたが、このような実装で問題ないでしょうか？

2022-01-04 10:11 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +const FlowCard = ({ title, createdAt }: FLowListType) => (
```diff
- <div key={flow.id}>
-  <FlowCard title={flow.title} createdAt={flow.createdAt} />
+  <FlowCard key={flow.id} title={flow.title} createdAt={flow.createdAt} />
-</div>
```
それでもできますが、こちらのほうが望ましいですね！

2022-01-04 10:13 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +const FlowCard = ({ title, createdAt }: FLowListType) => (
あと、FlowListに関しても直接flowsなどのダミーデータを使うのではなく、propsとして渡されたものを使うようにすると更にいい感じになるかなと思いました！

2022-01-06 07:40 UTC, DuGlaser requested changes
@shinooooo 
レビューしましたので確認お願いします！

2022-01-06 07:40 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +    </svg>
再利用可能だと思うのでcomponentsディレクトリ以下にiconsみたいなディレクトリを作ってその中に入れる形にしてほしいです！

2022-01-06 07:41 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +    </svg>
あとこのアイコンは自作したものですか？それともどこか他のところから持ってきたものですか？

2022-01-06 07:44 UTC, shinooooo commented on frontend/src/components/new/FlowListComponent.tsx
> +    </svg>
これはモック作成のため、hackmdのサイトから流用して仮置きしているものなので自作ではありません。

2022-01-06 07:49 UTC, DuGlaser commented on frontend/src/components/new/FlowListComponent.tsx
> +    </svg>
それはちょっと権利的に問題がありそうなのでアイコンを変えましょう！
chakraにもiconが組み込まれているのですが数が少なく正直微妙という感じなのですが、他のライブラリと統合させることができます！
以下にある通り今回はreact-iconsを使う形にしましょう！
https://chakra-ui.com/docs/media-and-icons/icon#using-a-third-party-icon-library
https://react-icons.github.io/react-icons/search?q=kebab

2022-01-06 14:24 UTC, DuGlaser requested changes
@n0s3nsE 
お疲れ様です！五月雨式になってしまい申し訳ないのですが、レビューしましたのでご確認お願いします:pray:

2022-01-06 14:24 UTC, DuGlaser commented on frontend/src/css/Toolbar.module.css
> +}
こちら不要そうなので消していただけますか？

2022-01-06 14:24 UTC, DuGlaser commented on frontend/src/components/new/ToolbarComponent.tsx
> +/* eslint-disable react/no-children-prop */
こちらおそらく必要ないと思うのですがいかがでしょうか！

2022-01-06 14:24 UTC, DuGlaser commented on frontend/src/components/new/ToolbarComponent.tsx
> +            <option value="updated-desc">更新日時(降順)</option>
こちら、このままでもいいのですが以下のようにするとより良いと思います！
```tsx
const orderOptions = [
  { label: '作成日時(昇順)', value: 'created-asc' },
  { label: '作成日時(降順)', value: 'created-desc' },
  { label: '更新日時(昇順)', value: 'updated-asc' },
  { label: '更新日時(降順)', value: 'updated-desc' },
];

export const Toolbar = () => {
  return (
    <Box mx={'50px'} py={'20px'} borderBottom={'1px'}>
      <Flex>
        ...
        <Box>
          <Select
            placeholder="並び替え"
            borderRadius="none"
            focusBorderColor="none"
          >
            {orderOptions.map((order) => (
              <option value={order.value}>{order.label}</option>
            ))}
          </Select>
        </Box>
      </Flex>
    </Box>
  );
};
```

2022-01-06 16:17 UTC, n0s3nsE commented on frontend/src/components/new/ToolbarComponent.tsx
> +/* eslint-disable react/no-children-prop */
こちら削除すると、28行目で
```
(JSX attribute) children?: ReactNode
Do not pass children as props. Instead, nest children between the opening and closing tags.eslintreact/no-children-prop
```
と警告されるのですが、スルーという形で問題ないでしょうか？
警告のみで、実行はできるという状況です。

2022-01-06 16:18 UTC, n0s3nsE commented on frontend/src/components/new/ToolbarComponent.tsx
> +            <option value="updated-desc">更新日時(降順)</option>
了解です！
修正します。

2022-01-06 16:25 UTC, n0s3nsE commented on frontend/src/components/new/ToolbarComponent.tsx
> +            <option value="updated-desc">更新日時(降順)</option>
こちら、keyが必要と言われるのですが、何をkeyにするのが適当なんでしょうか？
order.valueで問題ないでしょうか。
適切な物があれば指摘お願いします！

2022-01-06 16:27 UTC, DuGlaser commented on frontend/src/components/new/ToolbarComponent.tsx
> +/* eslint-disable react/no-children-prop */
今回のケースだとコンポーネントのpropsとしてchildrenが来ることを期待しています。つまり以下のようなコンポーネントを期待しています！
```tsx
const Example = ({ children }) => {
  return <div>{children}</div>;
};
```

しかし今回のようにchildrenを使わないようなこともあります。そういうときは以下のようにchildrenがない型をつける必要があります！
```tsx
const Example: React.VFC = ({ children }) => {
  return <div>{children}</div>;
};
```

逆にchildrenがほしいときは`React.FC`という型を使う必要があります！
この辺は以下の記事にまとまっていそうなのでご参照ください！
https://qiita.com/tttocklll/items/c78aa33856ded870e843

2022-01-06 16:29 UTC, DuGlaser commented on frontend/src/components/new/ToolbarComponent.tsx
> +            <option value="updated-desc">更新日時(降順)</option>
> order.valueで問題ないでしょうか。

key は兄弟要素の中で一意であればよいので、こちらで大丈夫だと思います！
keyの役割などについては以下を見てもらえると解ると思います！
https://ja.reactjs.org/docs/lists-and-keys.html#keys

2022-01-06 16:36 UTC, n0s3nsE commented on frontend/src/components/new/ToolbarComponent.tsx
> +            <option value="updated-desc">更新日時(降順)</option>
把握しました。
ありがとうございます！

2022-01-06 16:36 UTC, n0s3nsE commented on frontend/src/components/new/ToolbarComponent.tsx
> +/* eslint-disable react/no-children-prop */
ありがとうございます🙏

2022-01-06 16:47 UTC, DuGlaser approved these changes
何度もありがとうございます！LGTMです！

2022-01-06 16:47 UTC, merged