Issue 58
ISC-BusinessFlow/BusinessFlow pull request #73
Opened 2022-01-16 14:24 UTC by n0s3nsE

途中です

2022-01-16 14:29 UTC, n0s3nsE commented
特に問題がなければ他のコンポーネントもこんな感じで作っていこうと思ってます

2022-01-16 14:48 UTC, DuGlaser commented
> 特に問題がなければ他のコンポーネントもこんな感じで作っていこうと思ってます

いいと思います:+1: ありがとうございます！

2022-01-17 05:21 UTC, n0s3nsE commented on frontend/src/components/Path/transition.tsx
> +  //プロトタイプではパスが斜めになる可能性があるため、終端の図形の角度を合わせるような処理を追加してます
プロトタイプではパスが斜めになる可能性があるため、終端の図形の角度を合わせるような処理を追加してます
本番では斜めにならないので、arrowAngleごと削除してしまって問題ないと思います

2022-01-17 05:21 UTC, n0s3nsE commented on frontend/src/components/Path/transmission.tsx
> +  //プロトタイプではパスが斜めになる可能性があるため、終端の図形の角度を合わせるような処理を追加してます
プロトタイプではパスが斜めになる可能性があるため、終端の図形の角度を合わせるような処理を追加してます
本番では斜めにならないので、arrowAngleごと削除してしまって問題ないと思います

2022-01-17 05:25 UTC, DuGlaser commented on frontend/src/components/Path/transition.tsx
> +  //プロトタイプではパスが斜めになる可能性があるため、終端の図形の角度を合わせるような処理を追加してます
ありがとうございます！
markerを使うともっとシンプルにできそうな気がします！
http://defghi1977.html.xdomain.jp/tech/svgMemo/svgMemo_07.htm

2022-01-17 05:41 UTC, n0s3nsE commented on frontend/src/components/Path/transition.tsx
> +  //プロトタイプではパスが斜めになる可能性があるため、終端の図形の角度を合わせるような処理を追加してます
早速のレビューありがとうございます！
markerを利用するように修正しておきます。

2022-01-19 04:19 UTC, DuGlaser requested changes

2022-01-19 06:35 UTC, DuGlaser approved these changes
ありがとうございます！LGTMです！

2022-01-19 06:35 UTC, merged