issue-92
ISC-BusinessFlow/BusinessFlow pull request #96
Opened 2022-01-26 06:41 UTC by n0s3nsE

2022-02-01 09:05 UTC, n0s3nsE commented
@DuGlaser @shinooooo 
遅くなりました。こちらレビューよろしくおねがいします～🙏

2022-02-01 09:29 UTC, DuGlaser requested changes
@n0s3nsE 
PRありがとうございます！レビューしましたのでご確認お願いします！

2022-02-01 09:29 UTC, DuGlaser commented on frontend/src/components/Path/label.tsx
>              height: '100%',
styleを使わないで以下のようChakraのプロパティにしたがって記述したほうがより良いかなと思いました！
```tsx
<Box
  w="full"
  h="full"
>
```
https://ja.reactjs.org/docs/faq-styling.html#are-inline-styles-bad

2022-02-01 09:29 UTC, DuGlaser commented on frontend/src/components/Task/displaytext.tsx
> +      >
こちらも同様にstyleを使わないでChakraのプロパティにしたがって記述したほうがより良いかなと思いました！

2022-02-01 09:29 UTC, DuGlaser commented on frontend/src/components/Task/label.tsx
>              height: '100%',
こちらも同様にstyleを使わないでChakraのプロパティにしたがって記述したほうがより良いかなと思いました！

2022-02-01 09:29 UTC, DuGlaser commented on frontend/src/components/Task/label.tsx
> +  };
こちらborderColorが指定されていなかったらcolorよりも少しくらい色を生成するというものになっていると思うのですが、autoBorderColorという関数名だとどういう色を生成するかはコードを読まないとわからないと思いました！
また、この関数は割と再利用可能な関数だと思うので`darken` などのutil関数を作成してそれを使う形がいいのかなと思いました！
なので`src/utils`に`darken`などの関数を入れて、それをここで使う形に変更しましょう！

2022-02-01 10:40 UTC, DuGlaser requested changes
@n0s3nsE 
ありがとうございます！細かいところになるのですが2点ほどレビューしましたので確認お願いします！

2022-02-01 10:40 UTC, DuGlaser commented on frontend/src/utils/darkenColor.ts
> +export const darkenColor = (color: string): string => {
割とふわっとしたレビューだったのにいい感じに読み取ってくれてありがとうございます！
今だと0x1eという値だけしか暗くできないと思うのですが、これを任意でできるようにするともっと良さそうだと思いました！(できれば10進数で指定できるといいですね！)

2022-02-01 10:40 UTC, DuGlaser commented on frontend/src/components/Task/label.tsx
> +      return darkenColor(color);
```diff
-   if (typeof borderColor !== 'undefined') {
-     return borderColor;
-   } else {
-     return darkenColor(color);
+   if (borderColor) return borderColor;
+   return darkenColor(color);
```
ちょっと細かいところになるのですが、これのほうが治そさそうな気がしました！
あとはできたらでいいのですが、useMemoを使えるのなおいいのかなと思いました！
https://ja.reactjs.org/docs/hooks-reference.html#usememo

2022-02-02 01:21 UTC, n0s3nsE commented
修正しました！
こんな感じでいかがでしょうか

2022-02-02 01:22 UTC, DuGlaser requested changes

2022-02-02 01:22 UTC, DuGlaser commented on frontend/src/utils/darkenColor.ts
> +export const darkenColor = (color: string, degree: number): string => {
すごく細かくなってしまうのですが、degreeよりはdiffとかのほうが適切かなと思いました :pray:

2022-02-02 01:25 UTC, DuGlaser commented on frontend/src/utils/darkenColor.ts
> +export const darkenColor = (color: string, degree: number): string => {
@n0s3nsE 
お疲れ様です！こちら細かいところになってしまうのですがレビューしましたのでご確認お願いします！

2022-02-02 01:54 UTC, n0s3nsE commented on frontend/src/utils/darkenColor.ts
> +export const darkenColor = (color: string, degree: number): string => {
修正しました～

2022-02-02 01:55 UTC, DuGlaser approved these changes
ありがとうございます！めちゃくちゃ見た目も良くなっていい感じだと思います！

2022-02-03 16:54 UTC, shinooooo approved these changes
遅れてすみません。
確認できました！

2022-02-03 16:55 UTC, merged